// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Anchor: typeof import('./src/components/anchor.vue')['default']
    Markdown: typeof import('./src/components/markdown.vue')['default']
  }
}

export { }
